# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DIGui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(766, 587)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(210, 550, 101, 31))
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 470, 191, 111))
        self.groupBox.setObjectName("groupBox")
        self.btnShowBlank = QtWidgets.QPushButton(self.groupBox)
        self.btnShowBlank.setGeometry(QtCore.QRect(10, 80, 121, 23))
        self.btnShowBlank.setObjectName("btnShowBlank")
        self.btnShowCalibration = QtWidgets.QPushButton(self.groupBox)
        self.btnShowCalibration.setGeometry(QtCore.QRect(10, 50, 121, 23))
        self.btnShowCalibration.setObjectName("btnShowCalibration")
        self.labelProj = QtWidgets.QLabel(self.groupBox)
        self.labelProj.setGeometry(QtCore.QRect(10, 20, 161, 16))
        self.labelProj.setObjectName("labelProj")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 350, 191, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 101, 20))
        self.label_2.setObjectName("label_2")
        self.lineExpTime = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineExpTime.setGeometry(QtCore.QRect(120, 20, 51, 20))
        self.lineExpTime.setObjectName("lineExpTime")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 101, 20))
        self.label_3.setObjectName("label_3")
        self.lineLayerHeight = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineLayerHeight.setGeometry(QtCore.QRect(120, 50, 51, 20))
        self.lineLayerHeight.setObjectName("lineLayerHeight")
        self.btnPrint = QtWidgets.QPushButton(Form)
        self.btnPrint.setGeometry(QtCore.QRect(630, 540, 131, 41))
        self.btnPrint.setObjectName("btnPrint")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 150, 191, 191))
        self.groupBox_3.setObjectName("groupBox_3")
        self.btnRefresh = QtWidgets.QPushButton(self.groupBox_3)
        self.btnRefresh.setGeometry(QtCore.QRect(10, 70, 75, 23))
        self.btnRefresh.setObjectName("btnRefresh")
        self.portCombo = QtWidgets.QComboBox(self.groupBox_3)
        self.portCombo.setGeometry(QtCore.QRect(10, 20, 161, 21))
        self.portCombo.setObjectName("portCombo")
        self.btnConnect = QtWidgets.QPushButton(self.groupBox_3)
        self.btnConnect.setGeometry(QtCore.QRect(90, 70, 81, 23))
        self.btnConnect.setObjectName("btnConnect")
        self.btnUp1mm = QtWidgets.QPushButton(self.groupBox_3)
        self.btnUp1mm.setGeometry(QtCore.QRect(10, 130, 75, 23))
        self.btnUp1mm.setObjectName("btnUp1mm")
        self.btnDown1mm = QtWidgets.QPushButton(self.groupBox_3)
        self.btnDown1mm.setGeometry(QtCore.QRect(10, 160, 75, 23))
        self.btnDown1mm.setObjectName("btnDown1mm")
        self.btnHomeZ = QtWidgets.QPushButton(self.groupBox_3)
        self.btnHomeZ.setGeometry(QtCore.QRect(10, 100, 75, 23))
        self.btnHomeZ.setObjectName("btnHomeZ")
        self.btnUp10mm = QtWidgets.QPushButton(self.groupBox_3)
        self.btnUp10mm.setGeometry(QtCore.QRect(90, 130, 75, 23))
        self.btnUp10mm.setObjectName("btnUp10mm")
        self.btnDown10mm = QtWidgets.QPushButton(self.groupBox_3)
        self.btnDown10mm.setGeometry(QtCore.QRect(90, 160, 75, 23))
        self.btnDown10mm.setObjectName("btnDown10mm")
        self.lineBaud = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineBaud.setGeometry(QtCore.QRect(10, 50, 111, 16))
        self.lineBaud.setObjectName("lineBaud")
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(210, 10, 540, 480))
        self.graphicsView.setObjectName("graphicsView")
        self.sliderLayer = QtWidgets.QSlider(Form)
        self.sliderLayer.setGeometry(QtCore.QRect(210, 500, 541, 19))
        self.sliderLayer.setOrientation(QtCore.Qt.Horizontal)
        self.sliderLayer.setObjectName("sliderLayer")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 171, 121))
        self.label.setStyleSheet("image: url(:/image/dlp.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(320, 560, 291, 23))
        self.progressBar.setProperty("value", 100)
        self.progressBar.setObjectName("progressBar")
        self.labelLayer = QtWidgets.QLabel(Form)
        self.labelLayer.setGeometry(QtCore.QRect(460, 520, 54, 12))
        self.labelLayer.setObjectName("labelLayer")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "加载图片文件夹"))
        self.groupBox.setTitle(_translate("Form", "投影仪控制"))
        self.btnShowBlank.setText(_translate("Form", "黑屏"))
        self.btnShowCalibration.setText(_translate("Form", "显示网格"))
        self.labelProj.setText(_translate("Form", "找不到投影仪"))
        self.groupBox_2.setTitle(_translate("Form", "曝光控制"))
        self.label_2.setText(_translate("Form", "曝光延时（毫秒）"))
        self.lineExpTime.setText(_translate("Form", "2000"))
        self.label_3.setText(_translate("Form", "层厚（毫米）"))
        self.lineLayerHeight.setText(_translate("Form", "0.05"))
        self.btnPrint.setText(_translate("Form", "Start Print"))
        self.groupBox_3.setTitle(_translate("Form", "打印机控制"))
        self.btnRefresh.setText(_translate("Form", "刷新"))
        self.btnConnect.setText(_translate("Form", "连接"))
        self.btnUp1mm.setText(_translate("Form", "Up 1mm"))
        self.btnDown1mm.setText(_translate("Form", "Down 1mm"))
        self.btnHomeZ.setText(_translate("Form", "ZHome"))
        self.btnUp10mm.setText(_translate("Form", "Up 10mm"))
        self.btnDown10mm.setText(_translate("Form", "Down 10mm"))
        self.lineBaud.setText(_translate("Form", "115200"))
        self.labelLayer.setText(_translate("Form", "0"))

import image_rc
